language: emacs-lisp
before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs &&
  - sudo apt-get update -qq &&
  - sudo apt-get install -qq emacs24 emacs24-el emacs24-common-non-dfsg;
  - curl -fsSkL https://raw.github.com/rejeep/cask.el/master/go | python
  - export PATH="/home/travis/.cask/bin:$PATH"
  - cask

env:
  - EMACS=emacs24

script:
  - make compile
  - make checkdoc
